### ISSUE TITLE
Addon fails to start

### ISSUE THREAD

**Issue by jujupointcom** [devmel/hass_airsend-addon#1]
Hi, 
When launching the add-ons, it fails to start. Logs display this (only) : "s6-overlay-suexec: fatal: can only run as pid 1".
Addon installed through a wget command into HA terminal.
HA (Home Assistant OS)
Home Assistant 2022.8.3
Supervisor 2022.08.3
Operating System 8.4
Any idea ?

**Comment by jujupointcom** [comment]
Hi, 
I have just downloaded the new version, but I still have the same error when launching the add-on.

**Comment by jouralexandre** [comment]
Hi,
You must first uninstall the addons before installing the new one.
