### ISSUE TITLE
Add-on does not work after update Home Assistant 2023.7.3

### ISSUE THREAD

**Issue by falconslag** [devmel/hass_airsend-addon#2]
Hi,

I just did the update to Home Assistant 2023.7.3 from Home Assistant 2023.7.2 and since then your add-on does not work anymore.
I have tried to stop/start, reconstruct, and even uninstall/install it without succes.

I have a "Exception: Transfer error RDJ Bureau Volet : 404". My configuration file have not changed.

I am joing both log files (Airsend module and Home Assistant)

I also notice that the module is using around 50% CPU.

I hope you will fix the issue.

[f5e830cd_airsend_2023-07-23T17-05-41.688Z.log](https://github.com/devmel/hass_airsend-addon/files/12139203/f5e830cd_airsend_2023-07-23T17-05-41.688Z.log)
[home-assistant_2023-07-23T17-08-18.432Z.log](https://github.com/devmel/hass_airsend-addon/files/12139210/home-assistant_2023-07-23T17-08-18.432Z.log)

Regards.
Sylvain

**Comment by falconslag** [comment]
Hi,

after investigation, I noticed I had a second instance running for testing purpose. I think it simply took the "lead" and lock the Airsend Duo when I fully restart my production environnement. I stopped the dev one, and everything went back to normal.

Sorry for opening this issue, which is not one.

Your component is amazingly great.

**Comment by titou4307** [comment]
I cannot made my airsend duo functionnaly
Same lof like you for the Airsend duo.....

You coud share your conf YAML if you are in local ?

Claude from france

**Comment by falconslag** [comment]
Hi Titou4307,

I am using the Airsend Home Assistant Module in Home Assistant OS.

I have split my configuration in multiple files, for the Airsend part, here it is :
- in configuration.yaml, just add
# Airsend Devmel
airsend: !include split-configuration/airsend.yaml

- split-configuration/airsend.yaml (where split-configuration is my folder where I store all configuration in separate files when possible)
devices:
  RDJ Bureau Volet:
    id: 98745
    type: 4055
    spurl: !secret spurl
    #apiKey: abc45e42c1786d24e4f23d46adc752ca34589123a12546654b2159f547562b123d459644d62789a213b11654f4562d10e001265644575963aa1565412c645961
    channel:
      id: 45126
      source: 10587502
  RDJ All Volets:
    id: 85412
    type: 4098
    spurl: !secret spurl
    #apiKey: a8215e42c1786d24e4f23d46456752ca34589123a12546654b2159f547562b123d459644d62789a213b11654f4562d10e001265644575963aa1565412c645961
    channel:
      id: 12584
      source: 7692927
  1 All Volets:
    id: 54129
    type: 4098
    spurl: !secret spurl
    #apiKey: abc45e42c1786d24e4f23d46456752ca34589123a12546654b2159f547562b123d459644d62789a213b11654f4562d10e001265644575963aa1565412c645441
    channel:
      id: 84523
      source: 284903

Note, the API key is commented, because it allows me to switch to the "cloud version" in case of issue. I then uncoumment it and comment the spurl lines instead.
All the configuration of the devices are exported from airsend.cloud in yaml. It allows you to download the file with all entry in "cloud mode"

And finally, I add an entry in the secrets.yaml file
spurl: sp://the_password@192.175.18.1

the password is written on module, and the IP address is the IP of you module. Use IP v4, not the IP v6 for local configuration.

this configuration works like a charm, is fast because not related to the cloud. I used to have some error 500 with the cloud service (unknow reason). The local configuration always works. And you can still use the appli on your smartphone in parallel. Just avoid using both at the same time (seconds) because there is a kind of lock set during couple of seconds. The 2nd action may fail. Simply retry 10 seconds after. The lock is temporary.

Hope it helps.

regards,
Sylvain from france too ;-)

**Comment by titou4307** [comment]
Hi

Thanks for this return.....
I will try to reconfigure my Auirsend Duo in the end of the day

For clear esplanation : 
If password is AbcDDEFGFFfflkl so it needeed to put spurl: sp://AbcDDEFGFFfflkl@192.175.18.1 ?

ApiKey is not needeed if we stay on local

And may be you must mask your ApiKey in your message if it is your ApiKey

Merci !!

**Comment by titou4307** [comment]
Hello

My conf does not function.....

In configuration.yaml : 

airsend:
  internal_url: "http://192.168.xxx.xxx:8123"
  devices:
    Volet Evier:
      id: 35890
      type: 4098
      #apiKey: !secret apiKey
      spurl: !secret spurl
      channel:
         id: 25455
         source: 53351
    Volet cuisine:
      id: 35918
      type: 4098
      #apiKey: !secret apiKey
      spurl: !secret spurl      
      channel:
         id: 25455
         source: 12391

In the file secret.yaml : 

apiKey: 1234567894422555555555555abdfkfegjkegjzergjzgjmlgjdfsgfkdjgkdsfjgklfdjgmdfgmsdflkgmsfjgklfgjg
spurl: sp://44m8Tqwzzzzzzzzzzzzzz@192.168.1.18

with 44m8Tqwzzzzzzzzzzzzzz is the password under airsend

**Comment by titou4307** [comment]
Hello
With the basic install (solution cloud....) all seems OK
I come to test with apikey and I can pilot all my cover .....

When I try the install in local I had this problem : 

https://github.com/devmel/hass_airsend/issues/7#issuecomment-1650705713

So the solution is to add the line : 

http://192.168.xxx.xxx:8123/

So with this solution I have not more the problem and the airsend is ok on cloud....

And yes I have the airsend addon and is running

**Comment by titou4307** [comment]
Hi Falcon

The support Airsend Devmel has updated the addon Airsend on the last days

I will try to install new addon version and will give a return here....

There in the log an internal address IP:port...
This address:port must be write in the file configuration YAML

It seems near the solution you have put in your docker....

**Comment by titou4307** [comment]
The new version of addon not function in local mode.....

But is function in cloud mod....

I have access with command line into container addon but it not appears the port to map between Host and container...
May be this is the problem

**Comment by falconslag** [comment]
Hi titou,

If you can log using ssh into your HA, can you try to do a ping of:
- the name of your airsend_add-on (Ex: ping fffe532e-airsend)
- ping of the IP of your airsend box

Maybe you have either a DNS issue preventing the resolution of the add-on's name or a more basic network error (routing or firewall, etc.).

I am on holidays, with limited access so I cannot do more currently.

PS: just in case, there is an add-on module in HASS for SSH to.

**Comment by titou4307** [comment]
Hello
I have done ping to the two address : 
- airsend-addon
- IP of the airsend box

The two ping are OK, there 0% of packet lost

I have note when I type on SSH under root the command "docker ps" there is none port openened or linked between the docker airsend addon and the host....
For example for the docker container Z2M there is 0.0.0.0:8485->8485/tcp.....
